apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-initdb
          configMap:
            name: mongo-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: http
  selector:
    app: mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/f5devcentral/spa-demo-app-api:sha-033b779
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: mongodb
            - name: INVENTORY_URL
              value: http://inventory:8002
            - name: RECOMMENDATIONS_URL
              value: http://recommendations:8001

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
        - name: spa
          image: ghcr.io/f5devcentral/spa-demo-app-spa:sha-033b779
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spa
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: spa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      containers:
        - name: recommendations
          image: ghcr.io/f5devcentral/spa-demo-app-recommendations:sha-033b779
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: recommendations
spec:
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: recommendations

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: ghcr.io/f5devcentral/spa-demo-app-inventory:sha-033b779
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: inventory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-dark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa-dark
  template:
    metadata:
      labels:
        app: spa-dark
    spec:
      containers:
        - name: spa-dark
          image: ghcr.io/f5devcentral/spa-demo-app-spa-dark:sha-033b779
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spa-dark
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: spa-dark
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ3ekNDQXRlZ0F3SUJBZ0lVR3lweVlDbk54eWlDdnlmM3huTkZvekNpalU0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZWXhDekFKQmdOVkJBWVRBbFZUTVFzd0NRWURWUVFJREFKWFFURVFNQTRHQTFVRUJ3d0hVMlZoZEhScwpaVEVMTUFrR0ExVUVDZ3dDUmpVeERqQU1CZ05WQkFzTUJVSnlaWGQ2TVJrd0Z3WURWUVFEREJCaWNtVjNlaTVtCk5XUmxiVzh1WTI5dE1TQXdIZ1lKS29aSWh2Y05BUWtCRmhGaWNtVjNjM3BBWmpWa1pXMXZMbU52YlRBZUZ3MHkKTWpBNE1UZ3lNREF6TUROYUZ3MHlNekE0TVRneU1EQXpNRE5hTUlHR01Rc3dDUVlEVlFRR0V3SlZVekVMTUFrRwpBMVVFQ0F3Q1YwRXhFREFPQmdOVkJBY01CMU5sWVhSMGJHVXhDekFKQmdOVkJBb01Ba1kxTVE0d0RBWURWUVFMCkRBVkNjbVYzZWpFWk1CY0dBMVVFQXd3UVluSmxkM291WmpWa1pXMXZMbU52YlRFZ01CNEdDU3FHU0liM0RRRUoKQVJZUlluSmxkM042UUdZMVpHVnRieTVqYjIwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFEYW9wc0NEdkprd0hDajRYeWlzcWptdjFiQXJpR1EzczFNZ3dOZmE1Y1RZSFJzSGZCOGFUeU1NRHM4CklnVDF2TVF1dW9HVVU5UFFmYzhKU2toOUZlMDhrYndobkxjZmxpZHdOdzhXa0Ria0RtdTRlZmdOTkgySVorSU8KNStKcEVkYW1BWUtUUCtpUkpQN2tmZzEyMnI5TGxrNjFtUGdEaEs0YjR2bCtKb2RPb3RGaW5sMk5DSUt4UThKRAp3aEtQOTQvM3JteElUYldZS3JNL1lVbGY4MG9tVFFJVDRPejQzcmhBWFh5clpiT2lqdnExUVhWaWhzU09nSHdaCklrcGZ5ek1LSUozd0ZSb1JKaVR1Slo0OERvODRHeWZJeWtja1E3THpwNHBTVEhGMTdsMnYvcVdPRmF6OHRwQ3QKbjZMT0lCTzllQ1VnL2swc3BhRnp6QW8vQUduREFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVC9USk5PU3lVVAppV0VteklaY1BUOW0vWTQwdERBZkJnTlZIU01FR0RBV2dCVC9USk5PU3lVVGlXRW16SVpjUFQ5bS9ZNDB0REFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCenBzZXF1VTRpRVA4MW90QlcKZDAvb1VyZzdld3paL0NhSHZRT0ltWkhSMERQbmFUZ25XcnNqZ1Bmc1p1dG5Wa0YxV1hQMEhhUmN5M3lTZGEwbgpodG05SzNLS2srYTl2ZFZIOFZ0V1k1VTNNQktBNXBRd1hIQjRxSTJ1bE5OdlRBQTNCcHAySE0wblkweEIwUG1wCmpNOEVlbmtLTDJHbTJTaEFjTC9RcnF5N0U5aUFTOURxYi81bWo2WEhGdWQxZXorL05pQ2wzYkJScEdWaTFNRU0KNDV5SkVEaHpnK1JTN1FpTUE2dVdLZjcrMUEwUkFpOVVoeFhBL3hTTWhOSDgyZU4wZUF0bU0xaEN2eTV6b3ppUApwb1ZMRW84VzlxZ28xUUxKQ2ZZZWxlVWFBTkI3TTViSXNQMFh4WVBhczQ1UUFBUmV1U1Y3MkxkTDVyOHhnbEJCCkRVT1cKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRGFvcHNDRHZKa3dIQ2oKNFh5aXNxam12MWJBcmlHUTNzMU1nd05mYTVjVFlIUnNIZkI4YVR5TU1EczhJZ1Qxdk1RdXVvR1VVOVBRZmM4SgpTa2g5RmUwOGtid2huTGNmbGlkd053OFdrRGJrRG11NGVmZ05OSDJJWitJTzUrSnBFZGFtQVlLVFAraVJKUDdrCmZnMTIycjlMbGs2MW1QZ0RoSzRiNHZsK0pvZE9vdEZpbmwyTkNJS3hROEpEd2hLUDk0LzNybXhJVGJXWUtyTS8KWVVsZjgwb21UUUlUNE96NDNyaEFYWHlyWmJPaWp2cTFRWFZpaHNTT2dId1pJa3BmeXpNS0lKM3dGUm9SSmlUdQpKWjQ4RG84NEd5Zkl5a2NrUTdMenA0cFNUSEYxN2wydi9xV09GYXo4dHBDdG42TE9JQk85ZUNVZy9rMHNwYUZ6CnpBby9BR25EQWdNQkFBRUNnZ0VCQU00RXFXSUFLYUtNdjlkOU04K3Y0SDVHMEgyUjJDbEYrVmhlbi8vN1J3bkkKT3d4aURlbDkxTU1ZODhoUEdqTmhJOUFRaU9mM01jSGx1d0M3RWFGazF2N2JLTmJYY0t0Lzl6dkRkaUZCMWFlQwplemtESFoxNzE4cUFjVUN3ZXVXZEhKR2pIS0thZHhER05yV2luaGRnT3lBRHk3bE5JbTlXU0NZWTlCWk9RZlB5CnM1RUtjVFRVcGVWeGJoSXJIQXpMRzRSc1JETUIvT015L3dFa3VLQ2I2WVdNZ3ZaZ1F0VjBIL1UyVHM3SXdyTHoKMWpPRFhjc3RUYkZmeGFIVDdyVFhVYkx4d3ZVSW04R09uQnJwdk1XeUQ1eXRxMjB1MGZUczJKcU1SMmRIcW1hUgpPem54TmZrbDc4VkFtcWRla0ZvWkl1Uzl1SS9Wcit4ZGVPd1htRk5XRnVrQ2dZRUEveEZyam9NdmErb0NTTU40CnE0bTJPWUVZaVNsMGtOYkZKSmRPeTFaalNwcklUVXdqM2ZXUmJyUDBHQno1YXBTamFrOVJCd3djL0lpZ2hTMjIKZGQzcXlRdnVZeVdrUWw5SU9RWVlMMit0YXJhMldFa0pzTHAvWW12TnZ5dHNvMXZhRlNQT0xHOUxCMTc5Z25rdgpldDRXcnQ1aGMyN0NraDk2TWFWb1F1amhjSlVDZ1lFQTIyOGJpeTFLdVdQZExhaUdoNkRtTXhXRmc2MzBsUjdJCitkR3NMem8vaGRSZ3hwZng4dmhwZmJFMnJHLzdHZVNvblhBdkxjbDlUb2pmUktDR0VIQkNMVjZNMzZpcmZ6TzAKTDlmdGJuZ1ZTdTRzSTE2aElhNzZ2L3ljWjRLb1ZSMzA2NGc0YW9URjlYUzdRZEM2UXJTNitydVgwNTYzTnhwTAo2MFJIYmpzbEl2Y0NnWUFjQ2FvdEREYVdRaTdtR0xhWEJKaEhVZTJFaGs0TjdjM1Y2OXY1ZGhHTURkK2V2NVBoCnZqQ3lYbzJpYU96eHprejRUcWUxZ3B0ZEZ4ZXVEQXhXZ0lKaWZ6RkJMTTRWamF1K3VQREhwaHNGOC9ldlZMZi8KK1VBdmJYSThaV1dYdjIwRmpkNEgvR1BlOTQ0ZVhYdmVvYk1VbmRWUWZ3aGNUNkY2KzVldVl6TUUwUUtCZ1FESQpmVmpXTGZpek1IbzZxRnJhZXZrNVBYV3kzWEsxK04yNTI0Z04wcE9OaklFcmtsSy9JNWNHLzY2cm1OajlUSDErCjg2dzNrbnhLRUNhbXhtQVhqdW40R0Fad3ArU2hvVFVGN2EwREhQYWZjc09qUVdmSnBkMTNJckFvcHlsME01MisKd2NTQ0ZuUGtrOVl3Q1N6Vm05bW5FMVZpUmdheWN2VmdyUTd5dVZseCt3S0JnSEZKeFZFWjNtT2NWbm5UbHNGNwo0blphMzNuVW82M3lCRHhsc1FtQmtUUlFuWS9yb05BYU56dFl4a3VSUURoMlEza0JabTVMVENsNmh0R2FBZFQ3CjRZbThqSTZsSVh5ZlV0a3VtR1paSG5yemIxTUN4UDlrZjQ2aFVRK3lRWGtaeDcreWg3S3dlWlFZZzJHMGNKOXEKTlZrZ2VWR3dtS09qNGFYODZVOXRlaU9ICi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: brewz-tls
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: jwk-secret
type: nginx.org/jwk
data:
  jwk: eyJrZXlzIjoKICAgIFt7CiAgICAgICAgImsiOiJabUZ1ZEdGemRHbGphbmQwIiwKICAgICAgICAia3R5Ijoib2N0IiwKICAgICAgICAia2lkIjoiMDAwMSIKICAgIH1dCn0K