---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: brewz
spec:
  host: brewz.f5demo.com
  tls:
    secret: brewz-tls
  upstreams:
    - name: spa
      service: spa
      port: 80
    - name: api
      service: api
      port: 8000
      healthCheck:
        enable: true
        path: /api/stats
        interval: 20s
        jitter: 3s
        port: 8000      
    - name: inventory
      service: inventory
      port: 8002
    - name: recommendations
      service: recommendations
      port: 8001
  routes:
    - path: /
      action:
        pass: spa
    - path: /api
      policies:
        - name: rate-limit-policy
        - name: waf-policy
        - name: jwt-policy        
      action:
        pass: api
      ## circuit breaker 404
      errorPages:
        - codes: [404]
          return:
            code: 404
            type: application/json
            body: |
              {\"msg\": \"Not allowed!\"}
            headers:
              - name: x-debug-original-status
                value: ${upstream_status}
      #errorPages: 401
        - codes: [401]
          return:
            code: 401
            type: application/json
            body: |
              {\"msg\": \"Authorization Required\"}
            headers:
              - name: x-debug-original-status
                value: ${upstream_status}                   
    - path: /api/inventory     
      action:
        proxy:
          upstream: inventory
          rewritePath: /api/inventory      
    - path: /images
      action:
        proxy:
          upstream: api
          rewritePath: /images
    - path: /api/recommendations
      action:
        proxy:
          upstream: recommendations
          rewritePath: /api/recommendations
