---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apPolicy: "default/brewz-api-security-policy"
    securityLog:
      enable: true
      apLogConf: "default/logconf"
      logDest: "elastic.1YpC1mwRni3z0i09fGF138j4@https://quickstart-es-http.monitoring.svc.cluster.local:9200"
